# Generated by Django 5.2.10 on 2026-06-15 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('polar', 'Polar'), ('bkash', 'Bkash')], max_length=20, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('display_label', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('team', 'Team')], max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_sites', models.IntegerField(default=1)),
                ('max_projects', models.IntegerField(default=10)),
                ('max_blogs', models.IntegerField(default=10)),
                ('max_team_members', models.IntegerField(default=1)),
                ('allow_custom_domain', models.BooleanField(default=False)),
                ('allow_remove_branding', models.BooleanField(default=False)),
                ('allow_api_access', models.BooleanField(default=False)),
                ('allow_full_analytics', models.BooleanField(default=False)),
                ('allow_all_templates', models.BooleanField(default=False)),
                ('allow_priority_support', models.BooleanField(default=False)),
                ('base_seats_included', models.IntegerField(default=1)),
                ('price_per_extra_seat_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('price_per_extra_seat_bdt', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('balance_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('provider_invoice_id', models.CharField(blank=True, max_length=255)),
                ('provider_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('bkash_payment_id', models.CharField(blank=True, max_length=255)),
                ('bkash_trx_id', models.CharField(blank=True, max_length=255)),
                ('pending_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BalanceTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='PlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], max_length=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('BDT', 'BDT')], max_length=3)),
                ('provider', models.CharField(choices=[('polar', 'Polar'), ('bkash', 'Bkash')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('provider_product_id', models.CharField(blank=True, max_length=255)),
                ('provider_price_id', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='billing.plan')),
            ],
            options={
                'unique_together': {('plan', 'interval', 'currency', 'provider')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='plan_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.planprice'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('BDT', 'BDT'), ('any', 'Any')], default='any', max_length=5)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('uses_count', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('one_time_per_user', models.BooleanField(default=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_plans', models.ManyToManyField(blank=True, to='billing.plan')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.promocode'),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('past_due', 'Past Due'), ('pending', 'Pending'), ('expired', 'Expired'), ('grace_period', 'Grace Period')], default='pending', max_length=20)),
                ('extra_seats', models.IntegerField(default=0)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('grace_period_end', models.DateTimeField(blank=True, null=True)),
                ('provider_subscription_id', models.CharField(blank=True, max_length=255)),
                ('provider_customer_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.plan')),
                ('plan_price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='billing.planprice')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.subscription'),
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
