# Generated by Django 5.2.10 on 2026-06-16 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprovider',
            name='name',
            field=models.CharField(choices=[('polar', 'Polar'), ('bkash', 'Bkash'), ('internal', 'Internal')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='planprice',
            name='provider',
            field=models.CharField(choices=[('polar', 'Polar'), ('bkash', 'Bkash'), ('internal', 'Internal')], max_length=20),
        ),
        migrations.CreateModel(
            name='PromotionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('duration_days', models.IntegerField(default=180)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('auto_apply_on_signup', models.BooleanField(default=False)),
                ('claim_code', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_granted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.plan')),
            ],
        ),
    ]
