# Generated by Django 5.2.10 on 2026-02-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='theme',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
