# Generated by Django 5.2.10 on 2026-02-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_site_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='font',
            field=models.CharField(default='inter', max_length=50),
        ),
        migrations.AddField(
            model_name='site',
            name='template',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
