# Generated by Django 5.2.10 on 2026-02-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_site_font_site_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='available_for_hire',
            field=models.BooleanField(default=False),
        ),
    ]
