# Generated by Django 5.2.10 on 2026-06-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_site_available_for_hire'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdomain',
            name='cloudflare_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
