# Generated by Django 5.2.10 on 2026-06-18 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_customdomain_cloudflare_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(default='default', max_length=100)),
                ('theme_key', models.CharField(default='default', max_length=100)),
                ('font_key', models.CharField(default='inter', max_length=100)),
                ('template_version', models.CharField(default='1.0.0', max_length=20)),
                ('config_overrides', models.JSONField(blank=True, default=dict)),
                ('config_additions', models.JSONField(blank=True, default=dict)),
                ('config_removals', models.JSONField(blank=True, default=dict)),
                ('config_ordering', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_config', to='portfolios.site')),
            ],
            options={
                'verbose_name': 'Portfolio Template Config',
                'verbose_name_plural': 'Portfolio Template Configs',
            },
        ),
        migrations.CreateModel(
            name='TemplateVersionMigrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=100)),
                ('from_version', models.CharField(max_length=20)),
                ('to_version', models.CharField(max_length=20)),
                ('changes_applied', models.JSONField(default=list)),
                ('migrated_at', models.DateTimeField(auto_now_add=True)),
                ('migrated_by', models.CharField(default='auto', max_length=255)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_logs', to='portfolios.portfoliotemplateconfig')),
            ],
            options={
                'verbose_name': 'Template Version Migration Log',
                'verbose_name_plural': 'Template Version Migration Logs',
                'ordering': ['-migrated_at'],
            },
        ),
    ]
