# Generated by Django 5.2.10 on 2026-06-25 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_portfoliotemplateconfig_templateversionmigrationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='site',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='portfoliotemplateconfig',
            name='theme_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='site',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SiteSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_meta_title', models.CharField(blank=True, max_length=60)),
                ('default_meta_description', models.TextField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='site_og/')),
                ('google_analytics_id', models.CharField(blank=True, max_length=50)),
                ('google_tag_manager_id', models.CharField(blank=True, max_length=50)),
                ('facebook_pixel_id', models.CharField(blank=True, max_length=50)),
                ('robots_default', models.CharField(choices=[('index,follow', 'Index, Follow (default)'), ('noindex,follow', 'No Index, Follow'), ('index,nofollow', 'Index, No Follow'), ('noindex,nofollow', 'No Index, No Follow')], default='index,follow', max_length=30)),
                ('page_meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='portfolios.site')),
            ],
            options={
                'verbose_name': 'Site SEO',
                'verbose_name_plural': 'Site SEOs',
            },
        ),
    ]
