# Generated by Django 5.2.10 on 2026-06-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_remove_site_meta_description_remove_site_meta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliotemplateconfig',
            name='layout_width',
            field=models.CharField(choices=[('narrow', 'Narrow'), ('default', 'Default'), ('wide', 'Wide'), ('full', 'Full Width')], default='default', max_length=20),
        ),
    ]
