# Generated by Django 5.2.10 on 2026-01-31 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=500)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('content', models.TextField(blank=True)),
                ('project_url', models.URLField(blank=True, help_text='Live project URL', null=True)),
                ('github_url', models.URLField(blank=True, help_text='Source code URL', null=True)),
                ('technologies', models.JSONField(blank=True, default=list, help_text='List of technologies used')),
                ('featured', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolios.site')),
            ],
            options={
                'ordering': ['-featured', 'order', '-created_at'],
                'unique_together': {('site', 'slug')},
            },
        ),
    ]
