# Generated by Django 5.2.10 on 2026-02-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL', null=True),
        ),
    ]
