# Generated by Django 5.2.10 on 2026-06-15 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0005_customdomain_cloudflare_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='Page path, e.g. "/" or "/projects/my-app"', max_length=500)),
                ('referrer', models.CharField(blank=True, default='', help_text='Full referrer URL', max_length=1000)),
                ('referrer_domain', models.CharField(blank=True, default='', help_text='Extracted referrer domain, e.g. github.com', max_length=253)),
                ('country', models.CharField(blank=True, default='', help_text='ISO-3166 country code, e.g. BD', max_length=2)),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('browser', models.CharField(blank=True, default='', help_text='Browser name, e.g. Chrome', max_length=50)),
                ('session_id', models.CharField(db_index=True, help_text='Anonymous session UUID, set by the public frontend', max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='portfolios.site')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['site', '-timestamp'], name='analytics_s_site_id_99a5d4_idx'), models.Index(fields=['site', 'path'], name='analytics_s_site_id_65c8f7_idx'), models.Index(fields=['site', 'session_id'], name='analytics_s_site_id_2fb5b6_idx')],
            },
        ),
    ]
