"""
Django settings for api project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-=cldztbc4jg&xl0!x673!*v2_=p$$eu)=7*f#d0#zs$44xx-h^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1,localhost,.vercel.app,api.limefolio.com', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    # Third-party apps
    'rest_framework',
    "rest_framework_simplejwt",
    'corsheaders',
    'oauth2_provider',
    'social_django',
    'drf_social_oauth2',
    'drf_spectacular',
    'storages',
    # Local apps
    'core',
    'portfolios',
    'projects',
    'experiences',
    'blog',
    'media',
    'analytics',
    'billing',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware should be at the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.auth.middleware.SiteDetectionMiddleware',  # Site detection from domain
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'limefolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'limefolio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
# Note: Django modules for using databases are not support in serverless
# environments like Vercel. You can use a database over HTTP, hosted elsewhere.

LOCAL_DB = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

FORCE_SQLITE = config('FORCE_SQLITE', default=False, cast=bool)

# Use PostgreSQL with DATABASE_URL, falling back to SQLite if not set
_database_url = config('DATABASE_URL', default='')
DATABASES = LOCAL_DB if FORCE_SQLITE else (
    {'default': dj_database_url.parse(_database_url)} if _database_url else LOCAL_DB
)


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Dhaka'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# AWS / S3 / R2 Settings

AWS_S3_CUSTOM_DOMAIN = config('AWS_S3_CUSTOM_DOMAIN', default=None)

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": config('AWS_ACCESS_KEY_ID', default=''),
            "secret_key": config('AWS_SECRET_ACCESS_KEY', default=''),
            "bucket_name": config('AWS_STORAGE_BUCKET_NAME', default=''),
            "endpoint_url": config('AWS_S3_ENDPOINT_URL', default=None),
            "region_name": config('AWS_S3_REGION_NAME', default='auto'),
            "custom_domain": AWS_S3_CUSTOM_DOMAIN,
            "object_parameters": {
                'CacheControl': 'max-age=86400',
            },
            "signature_version": 's3v4',
            "querystring_auth": config("AWS_QUERYSTRING_AUTH", default=False, cast=bool),
            # 'location': 'media', # Optional: if you want to put all media in a subfolder
        },
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Force WhiteNoise to find files even if STATIC_ROOT manifest is missing
WHITENOISE_USE_FINDERS = True

MEDIA_URL = f'https://{AWS_S3_CUSTOM_DOMAIN}/' if AWS_S3_CUSTOM_DOMAIN else '/media/'


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email Settings
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Django Sites Framework
SITE_ID = 1

# Authentication Backends
AUTHENTICATION_BACKENDS = (
    'drf_social_oauth2.backends.DjangoOAuth2',
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.github.GithubOAuth2',
)

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
        'drf_social_oauth2.authentication.SocialAuthentication',
        'core.auth.authentication.APIKeyAuthentication',
        'core.auth.authentication.DomainBasedAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
     'DATE_INPUT_FORMATS': ['%Y-%m-%d', '%Y-%m-%dT%H:%M:%S.%fZ'],
}

OAUTH2_PROVIDER = {
    'ROTATE_REFRESH_TOKEN': True,
    'REFRESH_TOKEN_GRACE_PERIOD_SECONDS': 10,
    'ACCESS_TOKEN_EXPIRE_SECONDS': 36000, # 36000 10 hours
    'REFRESH_TOKEN_EXPIRE_SECONDS': 2592000, # 30 days
}


ACTIVATE_JWT = True

# Social Auth - Google
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('GOOGLE_CLIENT_ID', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('GOOGLE_CLIENT_SECRET', default='')
SOCIAL_AUTH_GOOGLE_OAUTH2_SCOPE = [
    'https://www.googleapis.com/auth/userinfo.email',
    'https://www.googleapis.com/auth/userinfo.profile',
]

# Social Auth - GitHub
SOCIAL_AUTH_GITHUB_KEY = config('GITHUB_CLIENT_ID', default='')
SOCIAL_AUTH_GITHUB_SECRET = config('GITHUB_CLIENT_SECRET', default='')
SOCIAL_AUTH_GITHUB_SCOPE = ['user:email']

# CORS Settings
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='https://api.limefolio.com,https://limefolio.com,https://www.limefolio.com',
    cast=Csv()
)
# CSRF Settings
CSRF_TRUSTED_ORIGINS = ["https://api.limefolio.com"]

#x-forwarded proto
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# DRF Spectacular Settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Limefolio API',
    'DESCRIPTION': 'Portfolio SaaS Platform API - Multi-tenant portfolio website builder with custom domains, projects, experiences, and more.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/',
}

# Revalidation Settings
REVALIDATION_TOKEN = config('REVALIDATION_TOKEN', default=None)
PUBLIC_APP_DOMAIN = config('PUBLIC_APP_DOMAIN', default="limefolio.com")
PUBLIC_APP_URL = config('PUBLIC_APP_URL', default=f"https://public.{PUBLIC_APP_DOMAIN}")

# Cloudflare Settings
CLOUDFLARE_API_TOKEN = config('CLOUDFLARE_API_TOKEN', default=None)
CLOUDFLARE_ZONE_ID = config('CLOUDFLARE_ZONE_ID', default=None)

# Billing Settings
BILLING_GRACE_PERIOD_DAYS = config('BILLING_GRACE_PERIOD_DAYS', default=7, cast=int)
BKASH_PAYMENT_TIMEOUT_MINUTES = config('BKASH_PAYMENT_TIMEOUT_MINUTES', default=30, cast=int)
RENEWAL_REMINDER_DAYS_BEFORE = config('RENEWAL_REMINDER_DAYS_BEFORE', default=7, cast=int)

POLAR_ACCESS_TOKEN = config("POLAR_ACCESS_TOKEN", default="")
POLAR_WEBHOOK_SECRET = config("POLAR_WEBHOOK_SECRET", default="")
POLAR_ENVIRONMENT = config("POLAR_ENVIRONMENT", default="sandbox")

BKASH_APP_KEY = config("BKASH_APP_KEY", default="")
BKASH_APP_SECRET = config("BKASH_APP_SECRET", default="")
BKASH_USERNAME = config("BKASH_USERNAME", default="")
BKASH_PASSWORD = config("BKASH_PASSWORD", default="")
BKASH_BASE_URL = config("BKASH_BASE_URL", default="https://tokenized.sandbox.bka.sh/v1.2.0-beta")

