# Generated by Django 5.2.10 on 2026-02-05 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming'), ('framework', 'Framework/Library'), ('database', 'Database'), ('devops', 'DevOps/Cloud'), ('design', 'Design'), ('soft_skill', 'Soft Skill'), ('language', 'Language'), ('tool', 'Tool'), ('other', 'Other')], default='other', max_length=20)),
                ('proficiency', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Brief description of your experience with this skill')),
                ('years_of_experience', models.PositiveIntegerField(blank=True, help_text='Years of experience', null=True)),
                ('icon_url', models.URLField(blank=True, help_text='URL to skill icon/logo', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this skill prominently')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolios.site')),
            ],
            options={
                'ordering': ['-is_featured', 'category', 'order', 'name'],
                'unique_together': {('site', 'name')},
            },
        ),
    ]
