# Generated by Django 5.2.10 on 2026-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Direct URL to thumbnail image (overrides media thumbnail)', max_length=500),
        ),
    ]
