# Generated by Django 4.1.3 on 2026-01-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_apikey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customdomain',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='customdomain',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customdomain',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='customdomain',
            name='domain',
            field=models.CharField(db_index=True, max_length=253, unique=True),
        ),
        migrations.RemoveField(
            model_name='customdomain',
            name='is_primary',
        ),
    ]
