# Generated by Django 4.1.3 on 2026-01-29 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/')),
                ('video', models.FileField(blank=True, null=True, upload_to='media/%Y/%m/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/thumbnails/%Y/%m/')),
                ('alt', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Media caption or description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured/primary media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Media',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['content_type', 'object_id'], name='media_media_content_c23fc6_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['order'], name='media_media_order_0c0cd7_idx'),
        ),
    ]
