# Generated by Django 5.2.10 on 2026-01-31 17:46

import django.db.models.deletion
import media.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=media.models.media_file_upload_to)),
                ('video', models.FileField(blank=True, null=True, upload_to=media.models.media_file_upload_to)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=media.models.media_file_upload_to)),
                ('alt', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Media caption or description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured/primary media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Media',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='media_media_content_c23fc6_idx'), models.Index(fields=['order'], name='media_media_order_0c0cd7_idx')],
            },
        ),
    ]
